# Generated by Django 5.1.7 on 2025-03-14 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "code",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "new_code",
                    models.CharField(blank=True, editable=False, max_length=50),
                ),
                ("title", models.CharField(max_length=100)),
                ("year", models.PositiveSmallIntegerField()),
                ("lab_cat", models.CharField(max_length=1)),
                ("hours", models.PositiveSmallIntegerField()),
                ("weeks", models.PositiveSmallIntegerField()),
                ("grp_count", models.PositiveSmallIntegerField()),
                ("grp_assigned", models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group", models.CharField(max_length=10)),
                ("day", models.CharField(max_length=3)),
                ("time", models.CharField(max_length=9)),
                ("venue", models.CharField(max_length=10)),
                ("teaching_week", models.JSONField(default=list)),
                ("assigned", models.BooleanField(default=False)),
                (
                    "code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="website.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "supervisor",
                    models.CharField(blank=True, default="Not Set", max_length=100),
                ),
                (
                    "bachelor_degree",
                    models.CharField(blank=True, default="Not Set", max_length=100),
                ),
                (
                    "matriculation_date",
                    models.CharField(blank=True, default="Not Set", max_length=7),
                ),
                ("gs_duty", models.BooleanField(default=True)),
                ("lab_load", models.PositiveSmallIntegerField(default=4)),
                (
                    "past_assignments",
                    models.ManyToManyField(blank=True, to="website.course"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpecialRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lab_groups_locked",
                    models.PositiveSmallIntegerField(blank=True, default=0),
                ),
                ("faculty_contact", models.CharField(blank=True, max_length=100)),
                ("unavailable_slots", models.JSONField(blank=True, default=list)),
                (
                    "max_teaching_days",
                    models.PositiveSmallIntegerField(blank=True, default=5),
                ),
                ("justification", models.TextField(blank=True)),
                ("course_lock_approved", models.BooleanField(default=False)),
                ("availability_approved", models.BooleanField(default=False)),
                (
                    "course_lock",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.student",
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="website.group"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="website.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeachingPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ranking", models.PositiveSmallIntegerField()),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="website.course"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.student",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.UniqueConstraint(
                fields=("code", "group"), name="unique_group_code"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teachingpreference",
            unique_together={("student", "course")},
        ),
    ]
