# Generated by Django 5.1.7 on 2025-03-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialrequest",
            name="admin_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="specialrequest",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
