# Generated by Django 5.1.7 on 2025-03-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_specialrequest_admin_comments_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Group",
            new_name="Lab",
        ),
        migrations.RemoveConstraint(
            model_name="lab",
            name="unique_group_code",
        ),
        migrations.RenameField(
            model_name="assignment",
            old_name="course_group",
            new_name="course_lab",
        ),
        migrations.AddConstraint(
            model_name="lab",
            constraint=models.UniqueConstraint(
                fields=("code", "group", "day", "time", "venue"),
                name="unique_lab_entry",
            ),
        ),
    ]
