# Generated by Django 5.1.7 on 2025-03-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_rename_group_lab_remove_lab_unique_group_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="grp_count",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
