# Generated by Django 5.1.7 on 2025-03-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_alter_student_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllocationWeights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "odd_even_pair_weight",
                    models.IntegerField(
                        default=40,
                        help_text="Weight for assigning odd/even week pairs to the same student",
                    ),
                ),
                (
                    "course_variety_weight",
                    models.IntegerField(
                        default=30,
                        help_text="Weight for minimizing variety of courses assigned to each student",
                    ),
                ),
                (
                    "past_assignments_weight",
                    models.IntegerField(
                        default=20,
                        help_text="Weight for assigning courses a student has taught before",
                    ),
                ),
                (
                    "preference_weight",
                    models.IntegerField(
                        default=25, help_text="Weight for student preferences"
                    ),
                ),
                (
                    "workload_distribution_weight",
                    models.IntegerField(
                        default=15, help_text="Weight for fair workload distribution"
                    ),
                ),
            ],
        ),
    ]
