# Generated by Django 5.1.7 on 2025-03-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_allocationweights"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocationweights",
            name="permutation_count",
            field=models.IntegerField(
                default=30,
                help_text="Number of permutations to run for the allocation algorithm",
            ),
        ),
    ]
