# Generated by Django 5.1.7 on 2025-03-21 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0008_alter_allocationweights_past_assignments_weight_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="swaprequest",
            old_name="receiver_message",
            new_name="message",
        ),
        migrations.RemoveField(
            model_name="swaprequest",
            name="course",
        ),
        migrations.RemoveField(
            model_name="swaprequest",
            name="requester_message",
        ),
        migrations.AddField(
            model_name="swaprequest",
            name="agreement_file",
            field=models.FileField(blank=True, null=True, upload_to="swap_agreements/"),
        ),
        migrations.AlterField(
            model_name="swaprequest",
            name="receiver_lab",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receiver_swap_requests",
                to="website.lab",
            ),
        ),
        migrations.AlterField(
            model_name="swaprequest",
            name="requester_lab",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requester_swap_requests",
                to="website.lab",
            ),
        ),
    ]
