# Generated by Django 5.1.7 on 2025-03-22 04:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0009_rename_receiver_message_swaprequest_message_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SwapRequest",
        ),
    ]
