# Generated by Django 5.1.7 on 2025-03-22 08:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0010_delete_swaprequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="grp_assigned",
        ),
    ]
